package com.example.hcahealthcaretask.model

/** Data transfer model for the repository fields used by the list and detail screens. */
data class RepositoryDataItem(
    val allow_forking: Boolean,
    val archive_url: String? = "test",
    val archived: Boolean,
    val assignees_url: String? = "test",
    val blobs_url: String? = "test",
    val branches_url: String? = "test",
    val clone_url: String? = "test",
    val collaborators_url: String? = "test",
    val comments_url: String? = "test",
    val commits_url: String? = "test",
    val compare_url: String? = "test",
    val contents_url: String? = "test",
    val contributors_url: String? = "test",
    val created_at: String? = "test",
    val default_branch: String? = "test",
    val deployments_url: String? = "test",
    val description: String? = "test",
    val disabled: Boolean,
    val downloads_url: String? = "test",
    val events_url: String? = "test",
    val fork: Boolean,
    val forks: Int,
    val forks_count: Int,
    val forks_url: String? = "test",
    val full_name: String? = "test",
    val git_commits_url: String? = "test",
    val git_refs_url: String? = "test",
    val git_tags_url: String? = "test",
    val git_url: String? = "test",
    val has_discussions: Boolean,
    val has_downloads: Boolean,
    val has_issues: Boolean,
    val has_pages: Boolean,
    val has_projects: Boolean,
    val has_wiki: Boolean,
    val homepage: String? = "test",
    val hooks_url: String? = "test",
    val html_url: String? = "test",
    val id: Int,
    val is_template: Boolean,
    val issue_comment_url: String? = "test",
    val issue_events_url: String? = "test",
    val issues_url: String? = "test",
    val keys_url: String? = "test",
    val labels_url: String? = "test",
    val language: String? = "test",
    val languages_url: String? = "test",
    val license: License,
    val merges_url: String? = "test",
    val milestones_url: String? = "test",
    val mirror_url: Any,
    val name: String? = "test",
    val node_id: String? = "test",
    val notifications_url: String? = "test",
    val open_issues: Int,
    val open_issues_count: Int,
    val owner: Owner,
    val `private`: Boolean,
    val pulls_url: String? = "test",
    val pushed_at: String? = "test",
    val releases_url: String? = "test",
    val size: Int,
    val ssh_url: String? = "test",
    val stargazers_count: Int,
    val stargazers_url: String? = "test",
    val statuses_url: String? = "test",
    val subscribers_url: String? = "test",
    val subscription_url: String? = "test",
    val svn_url: String? = "test",
    val tags_url: String? = "test",
    val teams_url: String? = "test",
    val topics: List<String?>,
    val trees_url: String? = "test",
    val updated_at: String? = "test",
    val url: String? = "test",
    val visibility: String? = "test",
    val watchers: Int,
    val watchers_count: Int,
    val web_commit_signoff_required: Boolean
)